# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ARM Open Science Summer School 2024
author: the <a href="https://www.arm.gov/">ARM Open Science</a> Community
logo: tutorials/images/logos/arm_logo.png
copyright: "2024"

execute:
  # To execute notebooks via a Binder instead, replace 'cache' with 'binder'
  execute_notebooks: "off"
  timeout: 600
  allow_errors: False # cells with expected failures must set the `raises-exception` cell tag

# Add a few extensions to help with parsing content
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution
  myst_substitutions:
    hackweek: "ARM Open Science Summer School"
    dates: "May 19-24 2024"
    github_org_url: https://github.com/ARM-Development
    book_repo: "arm-summer-school-2024"
    contact_email: "mgrover@anl.gov"
    website_url: "https://arm-development.github.io/arm-summer-school-2024"
    jupyterhub_url: "https://jupyterhub.arm.gov"
    slack_workspace_url: "https://join.slack.com/t/armsummerschool2024/shared_invite/zt-2h95xclsk-0BV9uwXiyErmsTZsMbTyfQ"

sphinx:
  config:
    linkcheck_ignore: ["https://doi.org/*", "https://zenodo.org/badge/*", "https://adc.arm.gov/*"] # don't run link checker on DOI links since they are immutable
    nb_execution_raise_on_error: true # raise exception in build if there are notebook errors (this flag is ignored if building on binder)
    html_favicon: tutorials/images/logos/arm_logo.png
    html_last_updated_fmt: "%-d %B %Y"
    html_permalinks_icon: '<i class="fas fa-link"></i>'
    html_theme_options:
      home_page_in_toc: true
      repository_url: https://github.com/ARM-Development/arm-summer-school-2024 # Online location of your book
      repository_branch: main # Which branch of the repository should be used when creating links (optional)
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      github_url: https://github.com/ARM-Development/arm-summer-school-2024
      icon_links:
        - name: YouTube
          url: https://www.youtube.com/channel/UCoZPBqJal5uKpO8ZiwzavCw
          icon: fab fa-youtube-square
          type: fontawesome
      launch_buttons:
        jupyterhub_url: https://jupyterhub.arm.gov
        notebook_interface: jupyterlab
      logo_link: https://www.arm.gov
